name: location_ninja
description: location live project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0-403.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_map: ^3.1.0
  geolocator: ^9.0.2
  geocoding: ^2.1.0
  geocoder_buddy: ^1.0.1
  tuple: ^2.0.1
  latlong2: ^0.8.1
  positioned_tap_detector_2: ^1.0.4
  transparent_image: ^2.0.1
  async: ^2.11.0
  flutter_image: ^4.1.5
  vector_math: ^2.1.4
  proj4dart: ^2.1.0
  meta: ^1.9.1
  collection: ^1.17.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true
  assets:
    - assets/images/

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg


